# Generated by Django 3.2.7 on 2021-11-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=None)),
                ('address', models.CharField(max_length=200)),
                ('headcount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='UserParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('is_join', models.BooleanField(default=False)),
                ('is_like', models.BooleanField(default=False)),
                ('party_id', models.ForeignKey(db_column='party_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_party',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='content', max_length=100)),
                ('parent', models.ForeignKey(db_column='parent', default=None, on_delete=django.db.models.deletion.CASCADE, to='party.comment')),
                ('party', models.ForeignKey(db_column='party', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
