# Generated by Django 3.2.9 on 2021-11-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_interest_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('headcount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='UserParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField()),
                ('party_id', models.ForeignKey(db_column='party_id', on_delete=django.db.models.deletion.CASCADE, to='party.party')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_party',
            },
        ),
    ]
