# Generated by Django 3.2.7 on 2021-11-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(db_column='parent', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.comment'),
        ),
    ]
