# Generated by Django 3.2.7 on 2021-11-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_admin'),
        ('party', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(db_column='comment', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.comment')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_comment',
            },
        ),
    ]
