# Generated by Django 3.2.9 on 2021-11-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparty',
            name='is_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userparty',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userparty',
            name='is_host',
            field=models.BooleanField(default=True),
        ),
    ]
