# Generated by Django 3.2.9 on 2021-11-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_interest_interest'),
        ('party', '0003_auto_20211106_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparty',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userparty',
            name='is_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userparty',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userparty',
            name='party_id',
            field=models.ForeignKey(db_column='party_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party'),
        ),
        migrations.AlterField(
            model_name='userparty',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
