# Generated by Django 3.2.7 on 2021-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='category',
            field=models.CharField(default='기타', max_length=200),
        ),
    ]
