# Generated by Django 3.2.9 on 2021-11-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20211106_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='content', max_length=100)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='PartyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.comment')),
                ('party_id', models.ForeignKey(db_column='party_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party')),
            ],
            options={
                'db_table': 'party_comment',
            },
        ),
    ]
