# Generated by Django 3.2.9 on 2021-12-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_party_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='background',
            new_name='image',
        ),
    ]
