# Generated by Django 3.2.9 on 2021-11-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_image'),
        ('party', '0005_comment_partycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
