# Generated by Django 3.2.9 on 2021-11-04 11:33

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'interest',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.PathAndRename('user/'))),
                ('social_login', models.CharField(max_length=10, null=True)),
                ('social_id', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.ForeignKey(db_column='interest_id', on_delete=django.db.models.deletion.CASCADE, to='user.interest')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_interest',
            },
        ),
    ]
