# Generated by Django 3.2.9 on 2021-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
