# Generated by Django 3.2.9 on 2021-11-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
