# Generated by Django 3.2.9 on 2021-11-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_is_activate_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='detail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
