# Generated by Django 3.2.9 on 2021-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
